name: Build and Package MSI

on:
  workflow_dispatch: # Manual trigger

jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create local.properties file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > local.properties
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> local.properties

      - name: Run Gradle packageMsi
        shell: pwsh
        run: .\gradlew packageMsi

#      - name: Upload MSI artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: msi-artifact
#          path: path/to/generated/file.msi # Replace with the actual path to the generated MSI file
